<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-AHR2CD7I" failures="1" tests="4" name="listener.myTest2" time="0.015" errors="0" timestamp="2023-07-15T23:16:03 IST" skipped="1">
  <testcase classname="listener.myTest2" name="z" time="0.002">
    <system-out>
      <![CDATA[TC z is  Running
TC z is Success]]>
    </system-out>
  </testcase> <!-- z -->
  <testcase classname="listener.myTest2" name="w" time="0.001">
    <system-out>
      <![CDATA[TC w is  Running plz try again
TC w is Success]]>
    </system-out>
  </testcase> <!-- w -->
  <testcase classname="listener.myTest2" name="y" time="0.001">
    <skipped/>
    <system-out>
      <![CDATA[TC y is Skiped]]>
    </system-out>
  </testcase> <!-- y -->
  <testcase classname="listener.myTest2" name="x" time="0.011">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at listener.myTest2.x(myTest2.java:19)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
    <system-out>
      <![CDATA[TC x is Failled]]>
    </system-out>
  </testcase> <!-- x -->
  <system-out>
    <![CDATA[TC x is Failled
TC z is  Running
TC z is Success
TC w is  Running plz try again
TC w is Success
TC y is Skiped
TC a is  Running plz try again
TC a is Success
TC b is Failled
TC d is  Running
TC d is Success
TC c is Skiped]]>
  </system-out>
</testsuite> <!-- listener.myTest2 -->
